# Generated by Django 5.2.4 on 2025-07-17 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialForProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fabric')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producttype')),
            ],
        ),
    ]
