# Generated by Django 5.2.4 on 2025-07-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_fabric_length_alter_fabric_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fabric_images/'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='weight',
            field=models.FloatField(),
        ),
    ]
