# Generated by Django 5.2.4 on 2025-07-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_materialtransaction_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='length',
        ),
        migrations.RemoveField(
            model_name='fabric',
            name='weight',
        ),
        migrations.AddField(
            model_name='fabric',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='fabric',
            name='unit',
            field=models.CharField(choices=[('kg', 'Килограммы'), ('m', 'Метры'), ('pcs', 'Штуки')], default='kg', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fabrics/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
