# Generated by Django 5.2.4 on 2025-07-18 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_image_product_price_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialtransaction',
            name='length',
        ),
        migrations.RemoveField(
            model_name='materialtransaction',
            name='weight',
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fabrics/'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('m', 'м'), ('pcs', 'шт')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.fabric'),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'Приход'), ('out', 'Расход')], max_length=3),
        ),
    ]
