# Generated by Django 5.2.4 on 2025-07-18 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_materialtransaction_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fabric'),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход')], max_length=3),
        ),
    ]
