# Generated by Django 5.2.4 on 2025-07-18 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_materialtransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransaction',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.fabric'),
        ),
    ]
