# Generated by Django 5.2.4 on 2025-07-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'шт.'), ('kg', 'кг')], default='pcs', max_length=10),
        ),
    ]
